var express = require('express'),
    app = express(),
    fs = require('fs');
//    middleware = require('./middleware')(app, express),
//    config = require('./config'),
//    log = require('./utils/log');



var mysql      = require('mysql');
var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',
  password : 'password',
  database : 'tecdoc'
});
 
connection.connect();
var SQL = 'SELECT TYP_ID, MFA_BRAND, DES_TEXTS7.TEX_TEXT AS MOD_CDS_TEXT, TOF_DES_TEXTS.TEX_TEXT AS TYP_CDS_TEXT, TYP_PCON_START, TYP_PCON_END, TYP_CCM, TYP_KW_FROM, TYP_KW_UPTO, TYP_HP_FROM, TYP_HP_UPTO, TYP_CYLINDERS, TOF_ENGINES.ENG_CODE, DES_TEXTS2.TEX_TEXT AS TYP_ENGINE_DES_TEXT, DES_TEXTS3.TEX_TEXT AS TYP_FUEL_DES_TEXT, IFNULL(DES_TEXTS4.TEX_TEXT, DES_TEXTS5.TEX_TEXT) AS TYP_BODY_DES_TEXT, DES_TEXTS6.TEX_TEXT AS TYP_AXLE_DES_TEXT, TYP_MAX_WEIGHT FROM TOF_TYPES INNER JOIN TOF_MODELS ON MOD_ID = TYP_MOD_ID INNER JOIN TOF_MANUFACTURERS ON MFA_ID = MOD_MFA_ID INNER JOIN TOF_COUNTRY_DESIGNATIONS AS COUNTRY_DESIGNATIONS2 ON COUNTRY_DESIGNATIONS2.CDS_ID = MOD_CDS_ID AND COUNTRY_DESIGNATIONS2.CDS_LNG_ID = 16 INNER JOIN TOF_DES_TEXTS AS DES_TEXTS7 ON DES_TEXTS7.TEX_ID = COUNTRY_DESIGNATIONS2.CDS_TEX_ID INNER JOIN TOF_COUNTRY_DESIGNATIONS ON TOF_COUNTRY_DESIGNATIONS.CDS_ID = TYP_CDS_ID AND TOF_COUNTRY_DESIGNATIONS.CDS_LNG_ID = 16 INNER JOIN TOF_DES_TEXTS ON TOF_DES_TEXTS.TEX_ID = TOF_COUNTRY_DESIGNATIONS.CDS_TEX_ID LEFT JOIN TOF_DESIGNATIONS ON TOF_DESIGNATIONS.DES_ID = TYP_KV_ENGINE_DES_ID AND TOF_DESIGNATIONS.DES_LNG_ID = 16 LEFT JOIN TOF_DES_TEXTS AS DES_TEXTS2 ON DES_TEXTS2.TEX_ID = TOF_DESIGNATIONS.DES_TEX_ID LEFT JOIN TOF_DESIGNATIONS AS DESIGNATIONS2 ON DESIGNATIONS2.DES_ID = TYP_KV_FUEL_DES_ID AND DESIGNATIONS2.DES_LNG_ID = 16 LEFT JOIN TOF_DES_TEXTS AS DES_TEXTS3 ON DES_TEXTS3.TEX_ID = DESIGNATIONS2.DES_TEX_ID LEFT JOIN TOF_LINK_TYP_ENG ON LTE_TYP_ID = TYP_ID LEFT JOIN TOF_ENGINES ON ENG_ID = LTE_ENG_ID LEFT JOIN TOF_DESIGNATIONS AS DESIGNATIONS3 ON DESIGNATIONS3.DES_ID = TYP_KV_BODY_DES_ID AND DESIGNATIONS3.DES_LNG_ID = 16 LEFT JOIN TOF_DES_TEXTS AS DES_TEXTS4 ON DES_TEXTS4.TEX_ID = DESIGNATIONS3.DES_TEX_ID LEFT JOIN TOF_DESIGNATIONS AS DESIGNATIONS4 ON DESIGNATIONS4.DES_ID = TYP_KV_MODEL_DES_ID AND DESIGNATIONS4.DES_LNG_ID = 16 LEFT JOIN TOF_DES_TEXTS AS DES_TEXTS5 ON DES_TEXTS5.TEX_ID = DESIGNATIONS4.DES_TEX_ID LEFT JOIN TOF_DESIGNATIONS AS DESIGNATIONS5 ON DESIGNATIONS5.DES_ID = TYP_KV_AXLE_DES_ID AND DESIGNATIONS5.DES_LNG_ID = 16 LEFT JOIN TOF_DES_TEXTS AS DES_TEXTS6 ON DES_TEXTS6.TEX_ID = DESIGNATIONS5.DES_TEX_ID WHERE TYP_MOD_ID = 3520 ORDER BY MFA_BRAND,  MOD_CDS_TEXT, TYP_CDS_TEXT, TYP_PCON_START, TYP_CCM';

connection.query(SQL, function(err, rows, fields) {
    if (err) {
        console.log(err);
        connection.end();
    }
    fs.writeFile('./data/types/3520.json', JSON.stringify(rows), err => {
        if (err) console.log(err);
        console.log('JSON created');
        connection.end();
    })
});
